name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  intl: ^0.20.2
  firebase_auth: ^6.5.2
  google_sign_in: ^7.2.0
  google_fonts: ^8.1.0
  flutter_svg: ^2.2.0
  qr_flutter: ^4.1.0
  just_audio: ^0.10.5
  audioplayers: ^6.7.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/calendar/avatar_blue_wink.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/
    - assets/images/home/
    - assets/images/home/group_pics/
    - assets/images/home/group_pics/cats/
    - assets/images/home/podium/
    - assets/images/home/podium/characters/
    - assets/images/bills/
    - assets/images/calendar/
    - assets/images/settings/
    - assets/images/nav/
    - assets/images/BottomNavBG.png
    - assets/images/homeIcon.png
    - assets/images/Settings.png
    - assets/images/TopPanel.png
    - assets/images/calendarIcon.png
    - assets/images/coinIcon.png
    - assets/images/BillMainPanel.png
    - assets/images/BillSubPanel.png
    - assets/sounds/bubblePop.mp3
    - assets/sounds/bubblePop2.mp3
    - assets/sounds/delete.mp3
    - assets/sounds/done.mp3
    - assets/sounds/swipe.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900