// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ADMx_rFkGv9CQ_0YEYgLfNSGs1bD8VU',
    appId: '1:188727929955:web:617004f9b4f9df20531c56',
    messagingSenderId: '188727929955',
    projectId: 'baebble-first',
    authDomain: 'baebble-first.firebaseapp.com',
    storageBucket: 'baebble-first.firebasestorage.app',
    measurementId: 'G-48FB11QLE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPqvsmnkPoUzsBkBUgE1jvEm6likoWRrk',
    appId: '1:188727929955:android:dcbbde10d9c17eec531c56',
    messagingSenderId: '188727929955',
    projectId: 'baebble-first',
    storageBucket: 'baebble-first.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLd2khSh3iVrOYVTjnGcTqS_Rrp-jexMM',
    appId: '1:188727929955:ios:b102231f612a1e86531c56',
    messagingSenderId: '188727929955',
    projectId: 'baebble-first',
    storageBucket: 'baebble-first.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLd2khSh3iVrOYVTjnGcTqS_Rrp-jexMM',
    appId: '1:188727929955:ios:b102231f612a1e86531c56',
    messagingSenderId: '188727929955',
    projectId: 'baebble-first',
    storageBucket: 'baebble-first.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ADMx_rFkGv9CQ_0YEYgLfNSGs1bD8VU',
    appId: '1:188727929955:web:ea9b2893aa16b4cd531c56',
    messagingSenderId: '188727929955',
    projectId: 'baebble-first',
    authDomain: 'baebble-first.firebaseapp.com',
    storageBucket: 'baebble-first.firebasestorage.app',
    measurementId: 'G-P03CN4Y1EV',
  );

}