// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNHb06O2FupHZgXuQSZ0qpW5S9_tnJU4I',
    appId: '1:671894972446:web:0025a90ff3be928fbda60f',
    messagingSenderId: '671894972446',
    projectId: 'baebbletrying',
    authDomain: 'baebbletrying.firebaseapp.com',
    storageBucket: 'baebbletrying.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgYJwcgM-xcDB3cnitwsOisL-PFEvCPWU',
    appId: '1:671894972446:android:868aa1e0fbf093cfbda60f',
    messagingSenderId: '671894972446',
    projectId: 'baebbletrying',
    storageBucket: 'baebbletrying.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6zwVwQ8d1ue6Kqwl7hCrckVjlZx1a1pY',
    appId: '1:671894972446:ios:32327646e6c94443bda60f',
    messagingSenderId: '671894972446',
    projectId: 'baebbletrying',
    storageBucket: 'baebbletrying.firebasestorage.app',
    iosBundleId: 'com.example.fluttertry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6zwVwQ8d1ue6Kqwl7hCrckVjlZx1a1pY',
    appId: '1:671894972446:ios:32327646e6c94443bda60f',
    messagingSenderId: '671894972446',
    projectId: 'baebbletrying',
    storageBucket: 'baebbletrying.firebasestorage.app',
    iosBundleId: 'com.example.fluttertry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNHb06O2FupHZgXuQSZ0qpW5S9_tnJU4I',
    appId: '1:671894972446:web:68cfe7a7ce0858f6bda60f',
    messagingSenderId: '671894972446',
    projectId: 'baebbletrying',
    authDomain: 'baebbletrying.firebaseapp.com',
    storageBucket: 'baebbletrying.firebasestorage.app',
  );
}
